rule pandas_merge:
    input:
        # Give sample id as input key, paths as input values
        sample1 = "datasets/file1.tsv",
        sample2 = "datasets/file2.tsv"
    output:
        # Give the name of the column you want to merge as output key
        # and path as input values
        Thing = "merged.tsv",
        Tabbed = "tab_merge.tsv"
    message:
        "Merging {input}"
    threads: 1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 768, 8192)
        )
    log:
        "logs/merge.logs"
    wrapper:
        "https://raw.githubusercontent.com/tdayris/yawn/master/SnakemakeWrappers/pandamerge/1.0"
