rule cp_target:
    input:
        "source/A.txt"
    output:
        "destination/A.txt"
    params:
        extra = "",
        cold_storage = "../cold_storage.yaml"
    threads: 1
    conda: "../environment.yaml"
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 256, 768)
        )
    message:
        "Testing cp"
    log:
        "logs/cp.logs"
    wrapper:
        "https://github.com/tdayris/yawn/tree/master/SnakemakeWrappers/cp/8.25"
