name: cp (bash)
author: Thibault Dayris
description: Simple cp from bash.
input:
  - Any file.
output:
  - Any file.
notes: |
  Why ? Because on our cluster, there are some issues bith bash versions
  and it has to be taken out of any pipeline execution. So ... Here it goes.
