name: "FastQC_0_11_7"
description: "Generate fastq quality statistics and reporting"
authors:
  - Thibault Dayris
input:
  - fastq file
output:
  - HTML report file containing statistics
  - ZIP ball containing statistics
testing:
  - "cd test; snakemake --ue-conda -rp"
