rule PCA:
    input:
        "data/quant.tsv"
    output:
        "pca/quant_PC_1_PC_2.png",
        "pca/quant_PC_3_PC_4.png"
    message:
        "Building PCA over {input}"
    threads: 1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 768, 8192)
        )
    log:
        "logs/PCA.logs"
    params:
        conditions = {
            "Sample1": "A",
            "Sample2": "A",
            "Sample3": "B",
            "Sample4": "B"
        }
    wrapper:
        "https://raw.githubusercontent.com/tdayris/yawn/master/SnakemakeWrappers/PCA/1.0"
