name: MultiQC_1_6
description : "Aggregate QC reports with MultiQC"
authors:
  - Thibault Dayris
input:
  - Files or directories containing quality control files
output:
  - HTML report
testing:
  - "cd test; snakemake --ue-conda -rp"
